name: aurelien-mysql
volumes:
  data:
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aurelien
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    container_name: aurelien-mysql
    restart: unless-stopped
    volumes:
      - 'data:/var/lib/mysql'
    ports:
      - '3307:3306'